### ISSUE TITLE
Issue with Moon Rise.

### ISSUE THREAD

**Issue by purnasatyap** [vm75/sweph.dart#14]
Hi.  I am trying to get the value of Sun/Moon RIse/Set timings. 

I am failing at the Moon rise as it says 
"E/flutter (13740): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: star Moon not found"

Here is the code that I am using. 

    var SunSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN ,"Sun",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunset");
    print(SunSet);
    var MoonRise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_MOON ,"Moon",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_CALC_RISE, geoPos, 0.0, 0.0, 0.0);
    print("moonrise");

Can you please help me with the correct way to calculate the Hindu Sun/Moon Rise/Set?

**Comment by vm75** [comment]
Thanks for reporting this. I will look into it and get back.

**Comment by vm75** [comment]
@purnasatyap 
Use empty string for name. This is the documentation for swe_rise_trans:
    int32 ipl,               /* planet number, if planet or moon */
    char *starname,     /* star name, if star; must be NULL or empty, if ipl is used */

I will update the API to accept null as well and fix the doc.

**Comment by purnasatyap** [comment]
This is the updated code and the error below. 

var SunSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN ,"Sun",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunset");
    print(SunSet);
    var MoonRise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_MOON ,"",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_CALC_RISE, geoPos, 0.0, 0.0);
    print("moonrise");
    print(MoonRise);



I/flutter (15136): sunset
I/flutter (15136): 2460329.911243594
W/WindowOnBackDispatcher(15136): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(15136): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/flutter (15136): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: rise or set not found for planet 1

**Comment by vm75** [comment]
I tried adding this to the example on Windows:

    final jd =
        Sweph.swe_julday(2022, 6, 29, (2 + 52 / 60), CalendarType.SE_GREG_CAL);

    const longitude = 81 + 50 / 60.0;
    const latitude = 25 + 57 / 60.0;
    final geoPos = GeoPosition(longitude, latitude, 0.0);

    var SunSet = Sweph.swe_rise_trans(
        jd,
        HeavenlyBody.SE_SUN,
        "",
        SwephFlag.SEFLG_SIDEREAL,
        RiseSetTransitFlag.SE_BIT_HINDU_RISING,
        geoPos,
        0.0,
        0.0);
    print("sunset " + SunSet.toString());
    var MoonRise = Sweph.swe_rise_trans(
        jd,
        HeavenlyBody.SE_MOON,
        "",
        SwephFlag.SEFLG_SIDEREAL,
        RiseSetTransitFlag.SE_CALC_RISE,
        geoPos,
        0.0,
        0.0);
    print("moonrise " + MoonRise.toString());

and this is printed

    flutter: sunset 2459760.4917810718
    flutter: moonrise 2459760.517457499

**Comment by vm75** [comment]
works on Android as well

    Connecting to VM Service at ws://127.0.0.1:57086/-09VzlRI85Q=/ws
    I/flutter ( 9418): sunset 2459760.4917810718
    I/flutter ( 9418): moonrise 2459760.517457499

**Comment by purnasatyap** [comment]
Not sure. Still giving me an error.  

```
var Sun_Rise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , "Sun" , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunrise");
    print(Sun_Rise);
    var SunSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN ,"Sun",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunset");
    print(SunSet);
    var MoonRise = Sweph.swe_rise_trans(
        jd,
        HeavenlyBody.SE_MOON,
        "",
        SwephFlag.SEFLG_SIDEREAL,
        RiseSetTransitFlag.SE_CALC_RISE,
        geoPos,
        0.0,
        0.0);
    print("moonrise");
    print(MoonRise);
```

Output 

I/flutter (15629): sunrise
I/flutter (15629): 2460329.911243551
I/flutter (15629): sunset
I/flutter (15629): 2460329.911243551
E/flutter (15629): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: rise or set not found for planet 1
E/flutter (15629): #0      Sweph.swe_rise_trans.<anonymous closure> (package:sweph/sweph.dart:589:9)
E/flutter (15629): #1      using (package:sweph/src/utils.dart:111:31)
E/flutter (15629): #2      Sweph.swe_rise_trans (package:sweph/sweph.dart:574:12)

**Comment by vm75** [comment]
Is this in the included example, or is it a different app?
Wonder if it is some init issue.
I tried Sweph.init without any epheAssets, and it is still working for me. 
If you can create a minimal flutter project with the error and share, I can debug

**Comment by purnasatyap** [comment]
Forked out the example app. added a new screen where I would be seeing the Sun/Moon Rise Data.  Here is the code. 

```
import 'package:flutter/material.dart';
import 'package:sweph/sweph.dart';
import 'package:timezone/standalone.dart' as tz;

class AstrologyScreen extends StatefulWidget {
  @override
  _AstrologyScreenState createState() => _AstrologyScreenState();
}

class _AstrologyScreenState extends State<AstrologyScreen> {
  late String planetaryPositions;
  late String risetimes;

  @override
  void initState() {
    super.initState();
    double currentLatitude = 17.385044; // Your latitude value
    double currentLongitude = 78.486671; // Your longitude value
    planetaryPositions = calculatePlanetaryPositions(currentLatitude, currentLongitude);
    risetimes = calculateRiseTimes(currentLatitude, currentLongitude) as String;

  }

  String calculatePlanetaryPositions(double latitude, double longitude) {
    final now = DateTime.now();
    final jd = Sweph.swe_julday(now.year, now.month, now.day, now.hour + now.minute / 60.0, CalendarType.SE_GREG_CAL);

    Sweph.swe_set_sid_mode(SiderealMode.SE_SIDM_LAHIRI, SiderealModeFlag.SE_SIDBIT_NONE, 0.0, 0.0);

    String positions = 'Date & Time: ${now.toString()}\nLatitude: $latitude, Longitude: $longitude\n\n';

    // List of planets
    List<HeavenlyBody> planets = [
      HeavenlyBody.SE_SUN,
      HeavenlyBody.SE_MOON,
      HeavenlyBody.SE_MARS,
      HeavenlyBody.SE_MERCURY,
      HeavenlyBody.SE_JUPITER,
      HeavenlyBody.SE_VENUS,
      HeavenlyBody.SE_SATURN,
      HeavenlyBody.SE_TRUE_NODE, // Rahu (True Node)
    ];

    for (var planet in planets) {
      final pos = Sweph.swe_calc_ut(jd, planet, SwephFlag.SEFLG_SWIEPH);
      String zodiacSign = getZodiacSign(pos.longitude);
      String nakshatra = getNakshatra(pos.longitude);
      positions += '${Sweph.swe_get_planet_name(planet)} - Long: ${pos.longitude.toStringAsFixed(3)} (${zodiacSign}), Nakshatra: $nakshatra\n';
    }

    // Calculate Ketu (180 degrees from Rahu)
    final rahuPos = Sweph.swe_calc_ut(jd, HeavenlyBody.SE_TRUE_NODE, SwephFlag.SEFLG_SWIEPH);
    double ketuLon = rahuPos.longitude + 180;
    if (ketuLon > 360) ketuLon -= 360;
    String ketuSign = getZodiacSign(ketuLon);
    positions += 'Ketu - Longitude: ${ketuLon.toStringAsFixed(3)} (${ketuSign})\n';

    return positions;
  }

  DateTime julianDayToDateTime(double julianDay) {
    int J = julianDay.round() + 32044;
    int g = J ~/ 146097;
    int dg = J % 146097;
    int c = (dg ~/ 36524 + 1) * 3 ~/ 4;
    int dc = dg - c * 36524;
    int b = dc ~/ 1461;
    int db = dc % 1461;
    int a = (db ~/ 365 + 1) * 3 ~/ 4;
    int da = db - a * 365;
    int y = g * 400 + c * 100 + b * 4 + a;
    int m = (da * 5 + 308) ~/ 153 - 2;
    int d = da - (m + 4) * 153 ~/ 5 + 122;
    DateTime date = DateTime.utc(y - 4800 + (m + 2) ~/ 12, (m + 2) % 12 + 1, d + 1);

    // Convert fractional day to time
    double frac = julianDay - julianDay.floor();
    int totalSecs = (frac * 86400).round();
    int hour = totalSecs ~/ 3600;
    int minute = (totalSecs % 3600) ~/ 60;
    int second = totalSecs % 60;

    return DateTime.utc(date.year, date.month, date.day, hour, minute, second);
  }

  // Function to convert Julian DateTime to UTC DateTime
  DateTime julianToUtc(double julianDay) {
    final j2000 = julianDay - 2451545.0;
    final utc = DateTime.utc(2000).add(Duration(microseconds: (j2000 * 86400000000).round()));
    return utc;
  }

  Future<DateTime> utcToLocal(DateTime utcDateTime) async {
    await tz.initializeTimeZone();
    final String currentTimeZone = DateTime.now().timeZoneName;
    final location = await tz.getLocation(currentTimeZone);
    final tzDateTime = tz.TZDateTime.from(utcDateTime, location);

    return tzDateTime;
  }


  Future<String>  calculateRiseTimes(double latitude, double longitude) async {
    final now = DateTime.now();
    final jd = Sweph.swe_julday(now.year, now.month, now.day, now.hour + now.minute / 60.0, CalendarType.SE_GREG_CAL);

    print(jd);
 //   Sweph.swe_set_sid_mode(SiderealMode.SE_SIDM_LAHIRI, SiderealModeFlag.SE_SIDBIT_NONE, 0.0, 0.0);

    GeoPosition geoPos = GeoPosition(17.385044, 78.23432 );
    print(geoPos.latitude);

    print(RiseSetTransitFlag.SE_CALC_RISE.value);

    print(RiseSetTransitFlag.SE_CALC_SET.value);

    print(RiseSetTransitFlag.SE_BIT_HINDU_RISING.value);

    // var rsmi = RiseSetTransitFlag.SE_BIT_HINDU_RISING + RiseSetTransitFlag.SE_CALC_RISE;

    var SunRise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , "Sun" , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print('SunRise (Julian Day): $SunRise');
    // Convert Julian to UTC
    DateTime utcDateTime = julianToUtc(SunRise);
    print('UTC DateTime: $utcDateTime');

    // Convert UTC to local
    DateTime localDateTime = utcDateTime.toLocal();

    print('UTC DateTime: $utcDateTime');
    print('Local DateTime: $localDateTime');
    var Sun_Rise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , "Sun" , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunrise");
    print(Sun_Rise);
    var SunSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN ,"Sun",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("sunset");
    print(SunSet);
    var MoonRise = Sweph.swe_rise_trans(
        jd,
        HeavenlyBody.SE_MOON,
        "",
        SwephFlag.SEFLG_SWIEPH,
        RiseSetTransitFlag.SE_CALC_RISE,
        geoPos,
        0.0,
        0.0);
    print("moonrise");
    print(MoonRise);
    var MoonSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_MOON ,"Moon",SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print("moonset");
    print(MoonSet);


    String Sunrisevalue = 'Sun Rise : ${SunRise.toString()}';
    String Sunsetvalue = 'Sun Set : ${SunSet.toString()}';
    String Moonrisevalue = 'Moon Rise : ${MoonRise.toString()}';
    String Moonsetvalue = 'Moon Set : ${MoonSet.toString()}';

    String risevalue = Sunrisevalue + "\n" + Sunsetvalue + "\n" + Moonrisevalue + "\n" + Moonsetvalue;
    print("risevalue");
    print(risevalue);
    return risevalue;


  }


  String getNakshatra(double longitude) {
    final nakshatras = [
      "Ashwini", "Bharani", "Krittika", "Rohini", "Mrigashira",
      "Ardra", "Punarvasu", "Pushya", "Ashlesha", "Magha",
      "Purva Phalguni", "Uttara Phalguni", "Hasta", "Chitra",
      "Swati", "Vishakha", "Anuradha", "Jyeshta", "Mula",
      "Purva Ashadha", "Uttara Ashadha", "Shravana", "Dhanishta",
      "Shatabhisha", "Purva Bhadrapada", "Uttara Bhadrapada", "Revati"
    ];
    int index = (longitude / (360 / 27)).floor();
    return nakshatras[index % 27];
  }

  String getZodiacSign(double longitude) {
    final signs = [
      "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
      "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"
    ];
    int index = (longitude / 30).floor();
    return signs[index % 12];
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Vedic Astrology Positions')),
      body: Container(
        child: Column(
          children: <Widget> [
        Padding(
            padding: EdgeInsets.all(16.0), // Adjust the padding value as needed
            child: Text(planetaryPositions),
          ),
            Padding(
              padding: EdgeInsets.all(16.0), // Adjust the padding value as needed
              child: Text(risetimes),
            ),
     ]
    ),
      )

    );
  }
}
```

**Comment by vm75** [comment]
Could you try making main() async and adding `await Sweph.init();` before calling runApp?

**Comment by purnasatyap** [comment]
This is what I have in the init. 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
//  await setupTimezone();
  final stopwatch = Stopwatch()..start();
  // Only load the assets you need. By default will load none
  // Bundled assets are available in Sweph.bundledEpheAssets
  await Sweph.init(epheAssets: [
    "packages/sweph/assets/ephe/seas_18.se1", // For house calc
    "packages/sweph/assets/ephe/sefstars.txt", // For star name
    "packages/sweph/assets/ephe/seasnam.txt", // For asteriods
  ]);
/*
  runApp(MyApp(
    timeToLoad: stopwatch.elapsed,
  )); */
  runApp(MyApp());
}
```

**Comment by vm75** [comment]
ok will try it out then.

**Comment by vm75** [comment]
Found the issue. I am handling the swe_rise_trans return value incorrectly. swe_rise_trans  returns:
·     0 if a rising, setting or transit event was found;
·     -1  if an error occurred (usually an ephemeris problem);
·     -2  if a rising or setting event was not found because the object is circumpolar.
For some lat-lon combinations, it returns -2.

**Comment by purnasatyap** [comment]
So what would be the fix?  any interim work arounds?

**Comment by vm75** [comment]
for now, you can catch the error and ignore this particular string. not an elegant solution. i will try to get this fixed soon.

**Comment by vm75** [comment]
Fixed in version 2.10.3+17. 
The changes to the SDK are breaking and will need minor edits

**Comment by purnasatyap** [comment]
Rise/Set for both Sun and Moon are returning null values.  Am I doing anything wrong? 


```
    var SunRise = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_CALC_RISE, geoPos, 0.0, 0.0);
    print(SunRise);

    var SunRise1 = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_BIT_HINDU_RISING, geoPos, 0.0, 0.0);
    print(SunRise1);

    var SunSet = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_SUN , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_CALC_SET, geoPos, 0.0, 0.0);
    print(SunSet);

    var MoonRise1 = Sweph.swe_rise_trans(jd, HeavenlyBody.SE_MOON , SwephFlag.SEFLG_SIDEREAL, RiseSetTransitFlag.SE_CALC_RISE, geoPos, 0.0, 0.0);
    print(MoonRise1);
```
Output

I/flutter (32157): null
I/flutter (32157): null
I/flutter (32157): null
I/flutter (32157): null

**Comment by vm75** [comment]
No, nothing wrong. The call to swe_rise_trans:
  /// returns [double] for the time of the rising, setting or transit event or
  /// null if an event was not found because the object is circumpolar.

It depends on the geo position and time

**Comment by vm75** [comment]
You can also refer to the documentation of swe_rise_trans in https://www.astro.com/swisseph/swephprg.htm

**Comment by purnasatyap** [comment]
Great. Thank you.
