### ISSUE TITLE
v3 crashes on iOS and Android during init

### ISSUE THREAD

**Issue by timashev** [vm75/sweph.dart#21]
On iOS Simulator:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Creation failed, path = 'ephe_files' (OS Error: Read-only file system, errno = 30)
#0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
directory_impl.dart:124
#1      SwephPlatformProvider.init (package:sweph/src/ffi_provider.dart:39:15)
ffi_provider.dart:39
<asynchronous suspension>
#2      Sweph.init (package:sweph/sweph.dart:53:17)
```

On Android Emulator:
```
E/flutter (19748): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Creation failed, path = 'ephe_files' (OS Error: Read-only file system, errno = 30)
E/flutter (19748): #0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
E/flutter (19748): #1      SwephPlatformProvider.init (package:sweph/src/ffi_provider.dart:39:15)
E/flutter (19748): <asynchronous suspension>
E/flutter (19748): #2      Sweph.init (package:sweph/sweph.dart:53:17)
```

**Comment by vm75** [comment]
seems to work as expected @timashev . i have updated example to include an additional file during init. but if it is failing due to some other reason, provide code snippets or a minimal project with the issue
